# Generated by Django 6.0.4 on 2026-04-21 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='match',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Stadium latitude (e.g. 33.9716)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Stadium longitude (e.g. -6.8498)', max_digits=9, null=True),
        ),
    ]
