# Generated by Django 6.0.4 on 2026-05-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_booking_qr_code_match_latitude_match_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', help_text='User country/city used for match recommendations (e.g. Morocco)', max_length=100),
        ),
    ]
