# Generated by Django 6.0.4 on 2026-05-07 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_add_location_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='city',
            field=models.CharField(blank=True, default='', help_text='City / venue city (e.g. Casablanca)', max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='country',
            field=models.CharField(blank=True, default='', help_text='Country (e.g. Morocco, France, USA)', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.CharField(help_text='Auto-filled from city + country. You can also type a free-form venue name.', max_length=200),
        ),
    ]
